# analysis configs example

trackers: ['dimp']
parameters: [['dimp50', 'dimp18']]
datasets: 'otb'
plots: ['success', 'prec', 'norm_prec']

perturb: False

perturbations:
  -
    var: 'fog'
    mode: 'consistent'
    mode_args:
      severity: 3
  -
    var: 'fog'
    mode: 'smooth'
    mode_args: 
      order: 'ascending'
      max_level: 5
  -
    var: 'fog'
    mode: 'burst'
    mode_args:
      order: 'ascending'
      severity: 5
      burst_pos: null
  -
    var: 'fog'
    mode: 'random'
    mode_args: 
      max_pos_count: 1
      max_frame_count: 3
