# analysis configs example

tracker: 'dimp'
parameter: ['dimp50']
dataset: 'got10k_test'
plots: ['success', 'prec', 'norm_prec']

perturb: True

perturbations:
  -
    var: 'fog'
    mode: 'consistent'
    mode_args:
      severity: 3
  # -
  #   var: 'motion_blur'
  #   mode: 'smooth'
  #   mode_args: 
  #     order: 'ascending'
  #     max_level: 5
  # -
  #   var: 'motion_blur'
  #   mode: 'burst'
  #   mode_args:
  #     order: 'ascending'
  #     severity: 1
  #     burst_pos: null
  # -
  #   var: 'motion_blur'
  #   mode: 'random'
  #   mode_args: 
  #     max_pos_count: 1
  #     max_frame_count: 3